### ISSUE TITLE
Decentralized Identifiers (DIDs) v1.0 2020-05-29 > 2020-06-30 (??)

### ISSUE THREAD

**Issue by iherman** [w3c/i18n-request#120]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed:  Decentralized Identifiers (DIDs) v1.0
- URL of spec: https://www.w3.org/TR/did-core/

    Note, however, that the Working Group uses respec+ECHIDNA in such a way that each merge into the master branch creates a new version of the document on TR space. This also means that the document on TR changes often. We would therefore prefer if each comment referred to the dated URL-s rather than the undated one.
   
- Current Rec/Note phase? Working Draft phase heading toward CR. Note that we prepared the self test [1] around the FPWD phase, but the subsequent f2f meeting led to discussions that have resulted in a complete re-organization of the document, and preferred to wait for things to stabilize before contacting the horizontal review groups./

    [1] https://github.com/w3c/did-core/issues/104

- What and when is your next expected transition? Transition to CR, to be expected (late?) summer.

- What has changed since any previous review? N/a

- Any information arising from a self-review? The DID Core specification (which is a data model, essentially) does not deal with human readable texts at all. As a consequence, we have the impression that no serious i18n issue would arise.

- Where and how to file issues arising? Best is to use github issues at https://github.com/w3c/did-core/ 

- Pointer to any explainer for the spec? Not yet available.

Other comments: None.

Cc: @msporny @burnburn @brentzundel

**Comment by aphillips** [comment]
@iherman Thanks for the request. Can you give us a more concrete target date? Would end of June be appropriate for us to finish our review? Thanks.

**Comment by iherman** [comment]
@aphillips my apologies, I should have set this. Yes, end of June would be fine. Thx.

**Comment by xfq** [comment]
I have reviewed the spec and didn't found any:

* natural language text that would be read/searched by a user
* issues regarding character encoding
* markup elements/attributes
* local date/time/format

The term "character" are used in the [Method Schemes](https://www.w3.org/TR/2020/WD-did-core-20200421/#method-schemes) section without definition. This is usually a problem in other specs, but I think there is no ambiguity here since only ASCII lowercase letters and digits are allowed in a [method name](https://www.w3.org/TR/2020/WD-did-core-20200421/#generic-did-syntax).

I only filed a minor issue in the [Normalization](https://www.w3.org/TR/2020/WD-did-core-20200421/#normalization) section, pending discussion by i18n WG: https://github.com/w3c/i18n-activity/issues/927
