### ISSUE TITLE
EPUB 3.3, EPUB Reading Systems 3.3, and EPUB Accessibility 1.1 review; > 2021-11-xx (early review)

### ISSUE THREAD

**Issue by iherman** [w3c/i18n-request#151]
- Name of specs to be reviewed: 
    - EPUB 3.3 
        - URL of spec: https://www.w3.org/TR/epub-33/
        - Editors' draft: https://w3c.github.io/epub-specs/epub33/core/
    - EPUB Reading Systems 3.3
        - https://www.w3.org/TR/epub-rs-33/
        - https://w3c.github.io/epub-specs/epub33/rs/
    - EPUB Accessibility 1.1
        - https://www.w3.org/TR/epub-a11y-11/
        - https://w3c.github.io/epub-specs/epub33/a11y/ 

- Do you need a reply by a particular date? 

    Per charter the CR is planned for November 2021
    
- Please point to the results of your own self-review

    https://github.com/w3c/epub-specs/wiki/Internationalization-self-test-for-the-EPUB-3.3.-spec

- Where and how to file issues arising? 
    
    https://github.com/w3c/epub-specs/issues/
    
- Pointer to any explainer for the spec?

    - See the separate section “Background information for reviewers” on the [self-review results page](https://github.com/w3c/epub-specs/wiki/Internationalization-self-test-for-the-EPUB-3.3.-spec); this also explains why the review of these three documents are bound in one.
    - See also the EPUB 3 Overview WG Note: https://www.w3.org/TR/epub-overview-33/

## Other comments:

The charter of the EPUB WG has a very strong emphasis on backward compatibility: 

> Any existing valid EPUB 3.2 should remain valid under EPUB 3.X, unless it relies on features discovered to have serious issues (such as a security bug).

This does tie the WG's hands on possible changes, including possible i18n issues.

cc: @wareid @dauwhe @mattgarrish @shiestyle

**Comment by iherman** [comment]
Further information: i18n related issues are labeled separately in the WG's repository, see:

https://github.com/w3c/epub-specs/issues?q=is%3Aissue+is%3Aopen+label%3ACat-i18n

**Comment by xfq** [comment]
I have reviewed the specs.

Since EPUB is just a package and the real content are in XHTML/CSS/etc., there's very little natural language text that would be read/searched by a user in the EPUB format itself. The following is my summary, pending discussion by i18n WG.

NOTE: Please don't comment on this thread. The i18n WG will in due course send comments your way.

## EPUB 3.3

It is possible to associate language and direction metadata with the natural language metadata in EPUB (by using `xml:lang` and `dir`) and the EPUB file itself (by using `dc:language` and `dir`).

The content of the metadata items (title, authors, etc.) are defined as strings, so it is not possible to indicate language for spans of inline text where the language changes, just like `title` in HTML. For direction, it's possible to use the control characters in UBA.

The use of `rp` elements is discouraged because EPUB 3 Reading Systems are ruby-aware, which looks good to me.

The `dc:creator` and `dc:contributor` elements contain personal names, and they look good to me. It is possible to store the name in both Latin and native scripts using the `alternate-script` property.

I filed a couple of pending issues:

* https://github.com/w3c/i18n-activity/issues/1353
* https://github.com/w3c/i18n-activity/issues/1354

## EPUB Reading Systems 3.3

Filed https://github.com/w3c/i18n-activity/issues/1355

## EPUB Accessibility 1.1

The conformance properties of the [EPUB Accessibility Vocabulary](https://w3c.github.io/epub-specs/epub33/a11y/#app-vocab-properties) look OK because [xml:lang and dir](https://w3c.github.io/epub-specs/epub33/core/#sec-shared-attrs) are allowed on `meta`.

Since some people have difficulty reading vertical text and would like to switch to horizontal text instead. Maybe we can add a metadata item to indicate the primary writing mode of a EPUB publication (I don't know if it is suitable for this document, though).

**To i18n WG:** we should also take a look at this issue: https://github.com/w3c/epub-specs/issues/1455#issuecomment-789617935

**Comment by iherman** [comment]
@xfq thanks for your review. I have one comment, though, on the following remark:

> Since some people have difficulty reading vertical text and would like to switch to horizontal text instead. Maybe we can add a metadata item to indicate the primary writing mode of a EPUB publication (I don't know if it is suitable for this document, though).

The accessibility metadata collection (ie the `meta` elements) does not create a special metadata structure in EPUB; these are "just" additional metadata items that the author can put into the [metadata section](https://w3c.github.io/epub-specs/epub33/core/#sec-pkg-metadata) of the EPUB package document. This means that the `dir` attribute is automatically available for these metatada items, too.

**Comment by xfq** [comment]
I mean we can probably add a metadata item about discovering EPUB publications that can be rendered horizontally (or vertically). I don't think `dir` can be used for this use case.

There were some discussions in a clreq meeting about this topic. See: https://www.w3.org/2021/02/24-clreq-minutes.html#t01 (maybe you already know it)

**Comment by aphillips** [comment]
@iherman We're not done with our review yet. Please save commentary for discussion in individual comments submitted after the I18N WG has review them.

(I'm going to violate that to say that @xfq does not mean `dir` here. Bidirectional metadata is a different thing than page and block progression. Cf. https://www.w3.org/TR/css-writing-modes/#block-flow. I thought EPUB already had metadata for this, since vertically presented books often have a different page progression direction e.g. `vertical-rl` books are bound on the right side??)

**Comment by xfq** [comment]
All `needs-resolution` issues have been resolved. Moving to Completed.

**Comment by iherman** [comment]
Thanks @xfq !
