### ISSUE TITLE
DCAT 3 2022-05-10 > 2022-08-31

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/i18n-request#184]
We have conducted a self-review of our spec [DCAT 3](https://www.w3.org/TR/vocab-dcat-3/), and the results can be found at https://github.com/w3c/dxwg/issues/1504.

Please check our findings.

- Do you need a reply by a particular date?
End of August, Early September as we plan to move to CR in Autumn.

**Comment by himorin** [comment]
No mention to BCP47, https://github.com/w3c/dxwg/pull/1522/files need to be merged. (see https://github.com/w3c/dxwg/issues/959 also)
Otherwise, see no issue on i18n or cultural point.

memo:
Date/Time is encoded using ISO8601, but DCAT spec is not for direct presentation.
For RDF serialization, as in [RDF Literals and Base Directions](https://w3c.github.io/rdf-dir-literal/) document, storing dir/lang should be resolved in RDF spec.
[Example 15](https://www.w3.org/TR/vocab-dcat-3/#ex-adms-identifier) has one example for `foaf:name` with English-like name. Should be fine, since it's not multiple examples with specific cultural based.

**Comment by riccardoAlbertoni** [comment]
> No mention to BCP47, https://github.com/w3c/dxwg/pull/1522/files need to be merged. (see [w3c/dxwg#959](https://github.com/w3c/dxwg/issues/959) also) Otherwise, see no issue on i18n or cultural point.

We have merged w3c/dxwg#1522. Thanks.
