### ISSUE TITLE
UI Events Keyboard Events Code Values 2022-11-29 > 2023-01-31

### ISSUE THREAD

**Issue by LJWatson** [w3c/i18n-request#200]
### Name of your specification

UI Events Keyboard Events Code Values

### URL of your specification

https://w3c.github.io/uievents-code/ - Next 

### When does the review need to be finished?

2022-01-31

### What has changed since any previous review?

- File issues: https://github.com/w3c/uievents-key/issues/
- I18n considerations: https://w3c.github.io/uievents-code/#i18n
- I18n self-review: https://github.com/w3c/uievents-code/issues/35#issuecomment-1301289450

There is one comment arising from the self-review:

>"describes a format or data that is likely to need localisation":
>This specification defines values that are not intended for display to the user, although there
is nothing preventing sites from exposing these values.

**Comment by LJWatson** [comment]
@xfq do you know when your review might be completed? With thanks.

**Comment by aphillips** [comment]
@LJWatson Our review was completed on 9 December. There was one issue, which is w3c/uievents-code#36. I just added a comment to that issue in case there may be any confusion about it. I also note that the issue is still present in your spec and that the raised issue is editorial. Please let me know if you have any questions or concerns!!

_this is [I18N-ACTION-1236](https://www.w3.org/International/track/actions/1236)_

This was originally posted to #199, which was incorrect.
